apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: 2019-02-15T10:17:35Z
  generation: 12
  labels:
    app: avo-elasticsearch
    component: elasticsearch-qas
    role: master
  name: es-cluster-qas
  namespace: sc-avo2
  resourceVersion: "69685051"
  selfLink: /apis/apps/v1/namespaces/sc-avo2/statefulsets/es-cluster-qas
  uid: e9ab6c00-310a-11e9-9188-005056a0a32c
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: elasticsearch-qas
      role: master
  serviceName: elasticsearch-qas
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: elasticsearch-qas
        role: master
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ES_PLUGINS_INSTALL
          value: https://nexus.thematchbox.be/repository/maven-releases/be/thematchbox/TheMatchBox-Plugin-ES/2.0-build-10/TheMatchBox-Plugin-ES-2.0-build-10-6.6.0.zip
        - name: CLUSTER_NAME
          value: viaa-es-qas
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1000m -Xmx1000m
        - name: PROCESSORS
          value: "1"
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery-qas
        image: docker-registry.default.svc:5000/sc-avo2/es:qas
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: transport
          timeoutSeconds: 1
        name: es-cluster-qas
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_cluster/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: es-storage
        - mountPath: /elasticsearch/theMatchBox-VIAA_Demo.lic
          name: matchbox-lic
          subPath: theMatchBox-VIAA_Demo.lic
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - 'sysctl -w vm.max_map_count=262144 '
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 364Mi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: matchbox-lic
        name: matchbox-lic
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: es-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 9Gi
      storageClassName: vsphere-standard
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: es-cluster-qas-5c9f7c7bb5
  observedGeneration: 12
  readyReplicas: 3
  replicas: 3
  updateRevision: es-cluster-qas-5c9f7c7bb5
  updatedReplicas: 3
